# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: DocumentParser.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14\x44ocumentParser.proto\"-\n\x15\x44ocumentParserRequest\x12\x14\n\x0c\x66ile_content\x18\x01 \x01(\x0c\"\xe3\x01\n\x16\x44ocumentParserResponse\x12\x31\n\x05pages\x18\x01 \x03(\x0b\x32\".DocumentParserResponse.PagesEntry\x12\x37\n\x08metadata\x18\x02 \x03(\x0b\x32%.DocumentParserResponse.MetadataEntry\x1a,\n\nPagesEntry\x12\x0b\n\x03key\x18\x01 \x01(\x05\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x1a/\n\rMetadataEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x32[\n\x15\x44ocumentParserService\x12\x42\n\x0fprocessDocument\x12\x16.DocumentParserRequest\x1a\x17.DocumentParserResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'DocumentParser_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_DOCUMENTPARSERRESPONSE_PAGESENTRY']._options = None
  _globals['_DOCUMENTPARSERRESPONSE_PAGESENTRY']._serialized_options = b'8\001'
  _globals['_DOCUMENTPARSERRESPONSE_METADATAENTRY']._options = None
  _globals['_DOCUMENTPARSERRESPONSE_METADATAENTRY']._serialized_options = b'8\001'
  _globals['_DOCUMENTPARSERREQUEST']._serialized_start=24
  _globals['_DOCUMENTPARSERREQUEST']._serialized_end=69
  _globals['_DOCUMENTPARSERRESPONSE']._serialized_start=72
  _globals['_DOCUMENTPARSERRESPONSE']._serialized_end=299
  _globals['_DOCUMENTPARSERRESPONSE_PAGESENTRY']._serialized_start=206
  _globals['_DOCUMENTPARSERRESPONSE_PAGESENTRY']._serialized_end=250
  _globals['_DOCUMENTPARSERRESPONSE_METADATAENTRY']._serialized_start=252
  _globals['_DOCUMENTPARSERRESPONSE_METADATAENTRY']._serialized_end=299
  _globals['_DOCUMENTPARSERSERVICE']._serialized_start=301
  _globals['_DOCUMENTPARSERSERVICE']._serialized_end=392
# @@protoc_insertion_point(module_scope)
