services:
    api:
        command: bash -c "
            source /tmp/envfile
            && hypercorn --bind 0.0.0.0:5000 --reload app.main:app
            "
        volumes:
            - ./back_end:/app
            - storage:/tmp/storage

    celery-worker:
        command: celery -b "redis://redis:6379" -A app.ct_core worker --concurrency=1 -l info

    front:
        command: vite --host
        environment:
            NODE_ENV: development
            WATCHPACK_POLLING: true
        volumes:
            - ./front_end:/app
            - /app/node_modules/