services:
    front:
        command: vite --host
        environment:
            NODE_ENV: development
            WATCHPACK_POLLING: true
        volumes:
            - .:/app
            - node_modules:/app/node_modules/

volumes:
    node_modules:
