services:
    front:
        build: .
        image: clinical-trials-front-private:latest
        pull_policy: never
        command: serve -s dist -p 5173
        ports:
            - "5173:5173"
        env_file:
            - .env
        environment:
            NODE_ENV: production
