"""fk user_id ondelete cascade

Revision ID: a3952c9adbec
Revises:
Create Date: 2025-01-21 09:42:01.265279

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'a3952c9adbec'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_document_user_id_user', 'document', type_='foreignkey')
    op.create_foreign_key('fk_document_user_id_user', 'document', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('fk_refresh_token_user_id_user', 'refresh_token', type_='foreignkey')
    op.create_foreign_key('fk_refresh_token_user_id_user', 'refresh_token', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('fk_user_module_user_id_user', 'user_module', type_='foreignkey')
    op.create_foreign_key('fk_user_module_user_id_user', 'user_module', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('fk_user_resource_usage_user_id_user', 'user_resource_usage', type_='foreignkey')
    op.create_foreign_key('fk_user_resource_usage_user_id_user', 'user_resource_usage', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('fk_user_role_user_id_user', 'user_role', type_='foreignkey')
    op.create_foreign_key('fk_user_role_user_id_user', 'user_role', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('fk_user_subscription_user_id_user', 'user_subscription', type_='foreignkey')
    op.create_foreign_key('fk_user_subscription_user_id_user', 'user_subscription', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('fk_user_weight_profile_user_id_user', 'user_weight_profile', type_='foreignkey')
    op.create_foreign_key('fk_user_weight_profile_user_id_user', 'user_weight_profile', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_user_weight_profile_user_id_user', 'user_weight_profile', type_='foreignkey')
    op.create_foreign_key('fk_user_weight_profile_user_id_user', 'user_weight_profile', 'user', ['user_id'], ['id'])
    op.drop_constraint('fk_user_subscription_user_id_user', 'user_subscription', type_='foreignkey')
    op.create_foreign_key('fk_user_subscription_user_id_user', 'user_subscription', 'user', ['user_id'], ['id'])
    op.drop_constraint('fk_user_role_user_id_user', 'user_role', type_='foreignkey')
    op.create_foreign_key('fk_user_role_user_id_user', 'user_role', 'user', ['user_id'], ['id'])
    op.drop_constraint('fk_user_resource_usage_user_id_user', 'user_resource_usage', type_='foreignkey')
    op.create_foreign_key('fk_user_resource_usage_user_id_user', 'user_resource_usage', 'user', ['user_id'], ['id'])
    op.drop_constraint('fk_user_module_user_id_user', 'user_module', type_='foreignkey')
    op.create_foreign_key('fk_user_module_user_id_user', 'user_module', 'user', ['user_id'], ['id'])
    op.drop_constraint('fk_refresh_token_user_id_user', 'refresh_token', type_='foreignkey')
    op.create_foreign_key('fk_refresh_token_user_id_user', 'refresh_token', 'user', ['user_id'], ['id'])
    op.drop_constraint('fk_document_user_id_user', 'document', type_='foreignkey')
    op.create_foreign_key('fk_document_user_id_user', 'document', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###
