[build-system]
requires = ["setuptools>=69.0.0", "wheel"]
build-backend = "setuptools.build_meta"


[tool.ruff.format]
quote-style = "double"
docstring-code-format = true

[tool.ruff.lint]
select = ["E", "F", "W", "Q", "I"]

[tool.ruff]
line-length = 180
# include = ["src/**/*.py"]
