import pycountry
from spacy.matcher import PhraseMatcher

from clinicaltrials.resources import nlp

demonym_to_country_code = {'aruban': 'AW',
                           'afghan': 'AF',
                           'angolan': 'AO',
                           'anguillian': 'AI',
                           'albanian': 'AL',
                           'emirati': 'AE',
                           'argentinean': 'AR',
                           'armenian': 'AM',
                           'american samoan': 'AS',
                           'french': 'PM',
                           'antiguan': 'AG',
                           'barbudan': 'AG',
                           'australian': 'AU',
                           'austrian': 'AT',
                           'azerbaijani': 'AZ',
                           'burundian': 'BI',
                           'belgian': 'BE',
                           'beninese': 'BJ',
                           'burkinabe': 'BF',
                           'bangladeshi': 'BD',
                           'bulgarian': 'BG',
                           'bahraini': 'BH',
                           'bahamian': 'BS',
                           'bosnian': 'BA',
                           'herzegovinian': 'BA',
                           'belarusian': 'BY',
                           'belizean': 'BZ',
                           'bermudian': 'BM',
                           'bolivian': 'BO',
                           'brazilian': 'BR',
                           'barbadian': 'BB',
                           'bruneian': 'BN',
                           'bhutanese': 'BT',
                           'motswana': 'BW',
                           'central african': 'CF',
                           'canadian': 'CA',
                           'cocos islander': 'CC',
                           'swiss': 'CH',
                           'chilean': 'CL',
                           'ivorian': 'CI',
                           'cameroonian': 'CM',
                           'congolese': 'CG',
                           'cook islander': 'CK',
                           'colombian': 'CO',
                           'comoran': 'KM',
                           'cape verdian': 'CV',
                           'costa rican': 'CR',
                           'cuban': 'CU',
                           'christmas island': 'CX',
                           'caymanian': 'KY',
                           'cypriot': 'CY',
                           'czech': 'CZ',
                           'german': 'DE',
                           'djibouti': 'DJ',
                           'dominican': 'DO',
                           'danish': 'DK',
                           'algerian': 'DZ',
                           'ecuadorean': 'EC',
                           'egyptian': 'EG',
                           'eritrean': 'ER',
                           'sahrawi': 'EH',
                           'spanish': 'ES',
                           'estonian': 'EE',
                           'ethiopian': 'ET',
                           'finnish': 'FI',
                           'fijian': 'FJ',
                           'falkland islander': 'FK',
                           'faroese': 'FO',
                           'micronesian': 'FM',
                           'gabonese': 'GA',
                           'british': 'GB',
                           'georgian': 'GE',
                           'channel islander': 'JE',
                           'ghanaian': 'GH',
                           'gibraltar': 'GI',
                           'guinean': 'GN',
                           'guadeloupian': 'GP',
                           'gambian': 'GM',
                           'guinea-bissauan': 'GW',
                           'equatorial guinean': 'GQ',
                           'greek': 'GR',
                           'grenadian': 'GD',
                           'greenlandic': 'GL',
                           'guatemalan': 'GT',
                           'guamanian': 'GU',
                           'guyanese': 'GY',
                           'heard and mcdonald islander': 'HM',
                           'honduran': 'HN',
                           'croatian': 'HR',
                           'haitian': 'HT',
                           'hungarian': 'HU',
                           'indonesian': 'ID',
                           'manx': 'IM',
                           'irish': 'IE',
                           'iranian': 'IR',
                           'iraqi': 'IQ',
                           'icelander': 'IS',
                           'israeli': 'IL',
                           'italian': 'IT',
                           'jamaican': 'JM',
                           'jordanian': 'JO',
                           'japanese': 'JP',
                           'kazakhstani': 'KZ',
                           'kenyan': 'KE',
                           'kirghiz': 'KG',
                           'cambodian': 'KH',
                           'i-kiribati': 'KI',
                           'kiribati': 'KI',
                           'kittian and nevisian': 'KN',
                           'south korean': 'KR',
                           'kuwaiti': 'KW',
                           'laotian': 'LA',
                           'lebanese': 'LB',
                           'liberian': 'LR',
                           'libyan': 'LY',
                           'saint lucian': 'LC',
                           'liechtensteiner': 'LI',
                           'sri lankan': 'LK',
                           'mosotho': 'LS',
                           'lithuanian': 'LT',
                           'luxembourger': 'LU',
                           'latvian': 'LV',
                           'moroccan': 'MA',
                           'monegasque': 'MC',
                           'moldovan': 'MD',
                           'malagasy': 'MG',
                           'maldivan': 'MV',
                           'mexican': 'MX',
                           'marshallese': 'MH',
                           'macedonian': 'MK',
                           'malian': 'ML',
                           'maltese': 'MT',
                           'mongolian': 'MN',
                           'american': 'US',
                           'mozambican': 'MZ',
                           'mauritanian': 'MR',
                           'montserratian': 'MS',
                           'mauritian': 'MU',
                           'malawian': 'MW',
                           'malaysian': 'MY',
                           'namibian': 'NA',
                           'new caledonian': 'NC',
                           'nigerien': 'NE',
                           'norfolk islander': 'NF',
                           'nigerian': 'NG',
                           'nicaraguan': 'NI',
                           'niuean': 'NU',
                           'dutch': 'NL',
                           'norwegian': 'SJ',
                           'nepalese': 'NP',
                           'nauruan': 'NR',
                           'new zealander': 'NZ',
                           'omani': 'OM',
                           'pakistani': 'PK',
                           'panamanian': 'PA',
                           'pitcairn islander': 'PN',
                           'peruvian': 'PE',
                           'filipino': 'PH',
                           'palauan': 'PW',
                           'papua new guinean': 'PG',
                           'polish': 'PL',
                           'puerto rican': 'PR',
                           'north korean': 'KP',
                           'portuguese': 'PT',
                           'paraguayan': 'PY',
                           'french polynesian': 'PF',
                           'qatari': 'QA',
                           'romanian': 'RO',
                           'russian': 'RU',
                           'rwandan': 'RW',
                           'saudi arabian': 'SA',
                           'sudanese': 'SD',
                           'senegalese': 'SN',
                           'singaporean': 'SG',
                           'south georgia and the south sandwich islander': 'GS',
                           'saint helenian': 'SH',
                           'solomon islander': 'SB',
                           'sierra leonean': 'SL',
                           'salvadoran': 'SV',
                           'sammarinese': 'SM',
                           'somali': 'SO',
                           'south sudanese': 'SS',
                           'sao tomean': 'ST',
                           'surinamer': 'SR',
                           'slovak': 'SK',
                           'slovene': 'SI',
                           'swedish': 'SE',
                           'swazi': 'SZ',
                           'seychellois': 'SC',
                           'syrian': 'SY',
                           'chadian': 'TD',
                           'togolese': 'TG',
                           'thai': 'TH',
                           'tadzhik': 'TJ',
                           'tajik': 'TJ',
                           'tokelauan': 'TK',
                           'turkmen': 'TM',
                           'east timorese': 'TL',
                           'tongan': 'TO',
                           'trinidadian': 'TT',
                           'tunisian': 'TN',
                           'turkish': 'TR',
                           'tuvaluan': 'TV',
                           'taiwanese': 'TW',
                           'tanzanian': 'TZ',
                           'ugandan': 'UG',
                           'ukrainian': 'UA',
                           'uruguayan': 'UY',
                           'uzbekistani': 'UZ',
                           'saint vincentian': 'VC',
                           'venezuelan': 'VE',
                           'vietnamese': 'VN',
                           'ni-vanuatu': 'VU',
                           'wallis and futuna islander': 'WF',
                           'samoan': 'WS',
                           'yemeni': 'YE',
                           'south african': 'ZA',
                           'zambian': 'ZM',
                           'zimbabwean': 'ZW'}

demonym_to_country = dict(
    [demonym, pycountry.countries.lookup(alpha_2)] for demonym, alpha_2 in demonym_to_country_code.items())

people_words = {
    "adults",
    "men",
    "women",
    "children",
    "infants",
    "toddlers",
    "sex workers",
    "communities",
    "community",
    "population",
    "males",
    "male adults",
    "females",
    "female adults",
    "individuals",
    "volunteers",
    "babies",
    "teenagers",
    "adolescents",
    "pregnant",
    "health workers",
    "immigrants"
}

patterns = {}



for demonym, country_code in demonym_to_country_code.items():
    if country_code not in patterns:
        patterns[country_code] = []
    patterns[country_code].append(f"{demonym}s")  # Tunisians
    for people_synonym in people_words:
        patterns[country_code].append(f"{demonym} {people_synonym}")  # Afghan people, Uzbek women, etc

phrase_matcher = PhraseMatcher(nlp.vocab, attr="LOWER")

for pattern_name, pattern_surface_forms in patterns.items():
    phrase_matcher.add(pattern_name, nlp.pipe(pattern_surface_forms))


def find_demonyms(doc) -> list:
    """
    Find the nationalities mentioned in the text that clearly refer to study subjects, e.g. Samoan males.
    :param text: the text of the protocol page
    :return: nationalities found as a list of tuples (PyCountry object and Match object).
    """
    country_matches = []

    matches = list(phrase_matcher(doc))
    for phrase_match in matches:
        matched_country = nlp.vocab.strings[phrase_match[0]]
        country_matches.append((matched_country, phrase_match))

    # matches = demonym_regex.finditer(text)
    # for match in matches:
    #     matched_country = demonym_to_country[match.groups()[0].upper()]
    #     country_matches.append((matched_country, match))

    return country_matches
