services:
    api:
        build:
            context: .
            dockerfile: ./docker/api/Dockerfile
        image: clinical-trials-api-private:latest
        pull_policy: never
        restart: always
        command: bash -c "
            source /tmp/envfile
            && hypercorn --config=hypercorn-docker.toml app.main:app
            "
        ports:
            - "5000:5000"
        volumes:
            - storage:/tmp/storage
            - nltk_data:/tmp/nltk_data
        env_file:
            - .env
        depends_on:
            db:
                condition: service_healthy
            tika-grpc:
                condition: service_started
            celery-worker:
                condition: service_healthy
            celery-beat:
                condition: service_started

    db:
        image: postgres:latest
        restart: always
        ports:
            - "5432:5432"
        volumes:
            - postgres_data:/var/lib/postgresql/data/
        environment:
            PGUSER: postgres
            POSTGRES_HOST: db
            POSTGRES_PORT: 5432
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: 123QWE,./
            POSTGRES_DB: clinical_trials
        healthcheck:
            test: [ "CMD-SHELL", "pg_isready", "-h", "db", "-d", "clinical_trials", "-U", "postgres" ]
            interval: 30s
            timeout: 10s
            retries: 5
            start_period: 5s

    tika-grpc:
        build:
            context: .
            dockerfile: ./docker/tika-grpc/Dockerfile
        image: clinical-trials-tika-grpc-private:latest
        pull_policy: never
        restart: always
        command: java -jar /app/target/fcnlp-tika-grpc-1.0.1-SNAPSHOT-fat.jar
        ports:
            - "8888:8888"

    redis:
        image: "redis:7.2-alpine"
        restart: always
        ports:
            - "6379:6379"
        healthcheck:
            test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
            interval: 30s
            timeout: 10s
            retries: 5
            start_period: 5s

    celery-worker:
        image: clinical-trials-api-private:latest
        pull_policy: never
        restart: always
        command: celery -b "redis://redis:6379" -A app.ct_core worker --concurrency=5 -l info
        volumes:
            - storage:/tmp/storage
            - nltk_data:/tmp/nltk_data
        healthcheck:
            test: [ "CMD-SHELL", "celery -b redis://redis:6379 inspect ping --destination celery@$$HOSTNAME" ]
            interval: 30s
            timeout: 10s
            retries: 5
            start_period: 5s
        depends_on:
            redis:
                condition: service_healthy

    celery-beat:
        image: clinical-trials-api-private:latest
        pull_policy: never
        restart: always
        command: celery -b "redis://redis:6379" -A app.ct_core beat -l info -s /tmp/celerybeat-schedule
        volumes:
            - storage:/tmp/storage
            - nltk_data:/tmp/nltk_data
        depends_on:
            redis:
                condition: service_healthy
            celery-worker:
                condition: service_healthy

volumes:
    postgres_data:
    nltk_data:
    storage:
